name: rpo-cuda
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch == 2.4.0
      - torchvision == 0.19.0
      - diffusers == 0.30.2
      - transformers == 4.44.0
      - numpy == 1.26.4
      - tqdm == 4.66.5
      - typed-argument-parser == 1.10.0
      - gitpython == 3.1.43
      - h5py == 3.11.0
      - datasets == 2.21.0
      - matplotlib == 3.8.4
      - latex == 0.7.0
      - ftfy == 6.2.0
      - tensorboard == 2.16.2
      - Jinja2 == 3.1.3
      - torchmetrics == 1.4.0
      - accelerate == 0.33.0
      - peft== 0.7.0