name: rpo-cuda
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch == 2.5.1+cu121
      - torchvision == 0.20.1+cu121
      - diffusers == 0.30.2
      - transformers == 4.46.1
      - numpy == 1.26.4
      - tqdm == 4.66.6
      - datasets == 3.1.0
      - jinja2 == 3.1.3
      - torchmetrics == 1.4.0
      - accelerate == 1.1.0
      - peft == 0.13.2